minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - lefthook
  - prisma
  - unrs-resolver

scriptsPrependNodePath: true
