name: EditorConfig
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
