name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: Build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run generate
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: pnpm test
      - name: Get installed playwright version
        id: playwright-version
        run: echo "version=$(pnpm list --depth 0 --json playwright | jq -r '.[0].devDependencies.playwright.version')" >> "$GITHUB_OUTPUT"
      - name: Cache playwright
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
      - name: Install playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - run: pnpm run build-storybook
      - run: >-
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue"
          "pnpm dlx http-server storybook-static --port 6006 --silent"
          "pnpm dlx wait-on http://127.0.0.1:6006 && pnpm run test-storybook -- --url=http://127.0.0.1:6006"
