name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run generate
      - run: pnpm run build
      - run: pnpm test
      - run: pnpm dlx playwright install --with-deps
      - run: pnpm run build-storybook
      - run: >-
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue"
          "pnpm dlx http-server storybook-static --port 6006 --silent"
          "pnpm dlx wait-on http://127.0.0.1:6006 && pnpm run test-storybook -- --url=http://127.0.0.1:6006"
      - run: pnpm run lint
