name: reviewdog
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run generate
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          level: error
          reporter: github-pr-review
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec prettier --write .
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          level: error
          tool_name: Prettier
  prisma:
    name: Prisma
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec prisma format
      - run: pnpm exec prisma-case-format --file prisma/schema.prisma
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          level: error
          tool_name: Prisma
